---
title: "data_wrangling_i"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
options(tibble.print_min = 3)
litters_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)
pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
rename(litters_data, GROUP = group, my_dogs = litter_number)
select(litters_data, litter_number, group, everything())
select(pups_data, litter_number, sex, pd_ears)
filter(litters_data, pups_born_alive >= 20)
filter(pups_data, sex == 2, pd_walk < 11)
# how to show wt_gain?
mutate(litters_data, wt_gain = gd18_weight - gd0_weight,
     group = tolower(group)
     )
mutate(pups_data, pivot_minus7 = pd_pivot - 7)
mutate(pups_data, pd_sum = pd_ears + pd_eyes + pd_pivot + pd_walk)
# arrange?
head(arrange(litters_data, group, gd_of_birth), 10)

```
```{r}
select(litters_data, group, litter_number, gd0_weight)
select(litters_data, litter_number, gd0_weight, pups_survive)
```
```{r}
# difference? 
select(litters_data, gd_of_birth:pups_survive)
select(litters_data, group, gd_of_birth:pups_survive)
```

```{r}
select(litters_data, -litter_number)
```

```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)
rename(litters_data, gest_0_weight = gd0_weight)
```

```{r}
select(litters_data, starts_with("gd"))
select(litters_data, litter_number, starts_with("pup"))
select(litters_data, litter_number, everything())
```

